baseURL = "https://tntech-ngin.net/"
languageCode = "en-us"
title = "ngin"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "docs"
paginate = 3

disableKinds = ["taxonomy", "term"]

[params]
    author = "Susmit"
    description = "Next Generation Internet Lab at Tennessee Tech University"
    githubUsername = "#"
    accent = "#bc4639"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "&copy; All rights reserved."

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 2

[[menu.main]]
    url = "/news/"
    name = "News"
    weight = 3

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 4

[[menu.main]]
    url = "/team/"
    name = "Team"
    weight = 5

#[[menu.main]]
#    url = "/about/"
#    name = "About"
#    weight = 6


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:sshannigrahi@tntech.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/tntech-ngin"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "#"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "#"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "#"
    name = "stack-overflow"
    weight = 5
